package com.phonerobot.app.robot

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Unit tests for ToyCarProtocol — the Kotlin mirror of toy_car_protocol_core.js.
 *
 * Expected byte sequences were generated by executing the JS reference
 * implementation (app/src/main/assets/toy_car_protocol_core.js) with Node:
 *   protocol.packMove(0x01, 30, 1000) → A5 04 10 01 1E E8 03 6D  ...
 * CRC-8/ROHC("123456789") = 0xF4 is also the canonical check value for
 * poly=0x07 init=0x00, confirming the JS reference itself is sound.
 * If these tests fail after editing the JS file, regenerate the vectors —
 * the two implementations must stay in lockstep.
 */
class ToyCarProtocolTest {

    // ── CRC8 vs JS reference + standard check value ─────────────

    @Test
    fun `crc8 matches CRC-8_ROHC standard check value`() {
        // Canonical check: CRC-8/ROHC of ASCII "123456789" = 0xF4
        val input = "123456789".map { it.code.toByte() }.toByteArray()
        assertEquals(0xF4, ToyCarProtocol.crc8(input))
    }

    @Test
    fun `crc8 of empty input is zero`() {
        assertEquals(0x00, ToyCarProtocol.crc8(ByteArray(0)))
    }

    @Test
    fun `crc8 matches JS reference for SYNC byte`() {
        // protocol.crc8([0xA5]) — from JS reference run
        assertEquals(0x72, ToyCarProtocol.crc8(byteArrayOf(0xA5.toByte())))
    }

    // ── Frame building vs JS reference vectors ──────────────────

    @Test
    fun `packMove matches JS reference forward`() {
        // protocol.packMove(0x01, 30, 1000)
        val expected = byteArrayOf(0xA5.toByte(), 0x04, 0x10, 0x01, 0x1E, 0xE8.toByte(), 0x03, 0x6D)
        val actual = ToyCarProtocol.buildFrame(
            ToyCarProtocol.CMD_MOVE,
            byteArrayOf(0x01, 30, 0xE8.toByte(), 0x03)
        )
        assertArrayEquals(expected, actual)
    }

    @Test
    fun `packMove matches JS reference backward`() {
        // protocol.packMove(0x02, 50, 500)
        val expected = byteArrayOf(0xA5.toByte(), 0x04, 0x10, 0x02, 0x32, 0xF4.toByte(), 0x01, 0x4B)
        val actual = ToyCarProtocol.buildFrame(
            ToyCarProtocol.CMD_MOVE,
            byteArrayOf(0x02, 50, 0xF4.toByte(), 0x01)
        )
        assertArrayEquals(expected, actual)
    }

    @Test
    fun `packTurn matches JS reference`() {
        // protocol.packTurn(0x01, 45, 30)
        val expected = byteArrayOf(0xA5.toByte(), 0x03, 0x20, 0x01, 0x2D, 0x1E, 0x44)
        val actual = ToyCarProtocol.buildFrame(
            ToyCarProtocol.CMD_TURN,
            byteArrayOf(0x01, 45, 30)
        )
        assertArrayEquals(expected, actual)
    }

    @Test
    fun `packStop matches JS reference`() {
        // protocol.packStop()
        val expected = byteArrayOf(0xA5.toByte(), 0x00, 0x40, 0x4F)
        assertArrayEquals(expected, ToyCarProtocol.buildFrame(ToyCarProtocol.CMD_STOP))
    }

    @Test
    fun `heartbeat matches JS reference for seq 0 and 255`() {
        assertArrayEquals(
            byteArrayOf(0xA5.toByte(), 0x01, 0x50, 0x00, 0xD6.toByte()),
            ToyCarProtocol.buildHeartbeat(0)
        )
        assertArrayEquals(
            byteArrayOf(0xA5.toByte(), 0x01, 0x50, 0xFF.toByte(), 0x25),
            ToyCarProtocol.buildHeartbeat(255)
        )
    }

    @Test
    fun `heartbeat seq wraps modulo 256`() {
        val frame = ToyCarProtocol.buildHeartbeat(256)
        assertEquals(0x00, frame[3].toInt() and 0xFF)
    }

    // ── Round trip: parseNotification accepts what buildFrame made ──

    @Test
    fun `parseNotification round-trips a built frame`() {
        val frame = ToyCarProtocol.buildFrame(ToyCarProtocol.CMD_MOVE, byteArrayOf(0x01, 30, 0xE8.toByte(), 0x03))
        val parsed = ToyCarProtocol.parseNotification(frame)
        // Downstream commands parse as UNKNOWN (only 0x81/0x82/0x83 are upstream),
        // but the frame itself must validate
        assertTrue("Expected valid, got error: ${parsed.error}", parsed.valid)
        assertEquals(ToyCarProtocol.CMD_MOVE, parsed.cmd)
    }

    // ── Upstream status parsing (MCU → phone) ────────────────────

    @Test
    fun `parseStatus extracts battery moving and current cmd`() {
        // MCU STATUS: battery=85, state=0x05 (moving|timedOp), error=0, cmdEcho=0x10
        val frame = byteArrayOf(0xA5.toByte(), 0x04, 0x81.toByte(), 85, 0x05, 0x00, 0x10, 0xD2.toByte())
        val parsed = ToyCarProtocol.parseNotification(frame)

        assertTrue(parsed.valid)
        assertEquals("STATUS", parsed.cmdName)
        assertEquals(85, parsed.data["battery"])
        assertEquals(true, parsed.data["moving"])
        assertEquals(false, parsed.data["fault"])
        assertEquals(true, parsed.data["timedOp"])
        assertEquals(0, parsed.data["errorCode"])
        assertEquals("Normal", parsed.data["errorName"])
        assertEquals(0x10, parsed.data["currentCmd"])
    }

    @Test
    fun `parseStatus reports motor stall fault`() {
        // battery=10, state=0x02 (fault), error=0x01 MotorStall
        val frame = byteArrayOf(0xA5.toByte(), 0x04, 0x81.toByte(), 10, 0x02, 0x01, 0x00, 0x8F.toByte())
        val parsed = ToyCarProtocol.parseNotification(frame)

        assertTrue(parsed.valid)
        assertEquals(true, parsed.data["fault"])
        assertEquals(false, parsed.data["moving"])
        assertEquals("MotorStall", parsed.data["errorName"])
    }

    @Test
    fun `parseHbAck extracts seq and battery`() {
        // HB_ACK: seq=42, battery=85, state=0x01 (moving)
        val frame = byteArrayOf(0xA5.toByte(), 0x03, 0x82.toByte(), 42, 85, 0x01, 0x6F)
        val parsed = ToyCarProtocol.parseNotification(frame)

        assertTrue(parsed.valid)
        assertEquals("HB_ACK", parsed.cmdName)
        assertEquals(42, parsed.data["seq"])
        assertEquals(85, parsed.data["battery"])
        assertEquals(true, parsed.data["moving"])
    }

    @Test
    fun `parseCmdDone maps result codes`() {
        val success = ToyCarProtocol.parseNotification(
            byteArrayOf(0xA5.toByte(), 0x02, 0x83.toByte(), 0x10, 0x00, 0xD3.toByte())
        )
        assertTrue(success.valid)
        assertEquals("CMD_DONE", success.cmdName)
        assertEquals("Success", success.data["resultName"])
        assertEquals(0x10, success.data["cmdEcho"])

        val aborted = ToyCarProtocol.parseNotification(
            byteArrayOf(0xA5.toByte(), 0x02, 0x83.toByte(), 0x20, 0xFF.toByte(), 0xD9.toByte())
        )
        assertTrue(aborted.valid)
        assertEquals("Aborted", aborted.data["resultName"])
    }

    // ── Corrupt frame rejection ──────────────────────────────────

    @Test
    fun `parseNotification rejects bad sync byte`() {
        val parsed = ToyCarProtocol.parseNotification(byteArrayOf(0x00, 0x01, 0x50, 0x00))
        assertFalse(parsed.valid)
        assertTrue(parsed.error!!.contains("SYNC"))
    }

    @Test
    fun `parseNotification rejects short frame`() {
        assertFalse(ToyCarProtocol.parseNotification(byteArrayOf(0xA5.toByte())).valid)
        assertFalse(ToyCarProtocol.parseNotification(ByteArray(0)).valid)
    }

    @Test
    fun `parseNotification rejects CRC corruption`() {
        val frame = ToyCarProtocol.buildFrame(ToyCarProtocol.CMD_HEARTBEAT, byteArrayOf(7))
        frame[frame.size - 1] = (frame[frame.size - 1].toInt() xor 0x01).toByte()  // flip CRC bit
        val parsed = ToyCarProtocol.parseNotification(frame)
        assertFalse(parsed.valid)
        assertTrue(parsed.error!!.contains("CRC mismatch"))
    }
}
